import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Next + Shopify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main className="mlb-xl">
                <article className="center">
                    <h2 className="text-3">Next + Shopify!</h2>
                </article>
            </main>
        </>
    );
}
